# Nerd Fonts for your IDE
# https://www.nerdfonts.com/font-downloads

brew tap homebrew/cask-fonts && brew install --cask font-3270-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-FiraMono-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-Inconsolata-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-Monofur-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-Overpass-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-UbuntuMono-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-agage-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-animo-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-anonymice-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-aurulentsansmono-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-bigblueterminal-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-bitstreamverasansmono-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-blexmono-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-caskaydia-cove-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-codenewroman-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-cousine-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-daddytimemono-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-dejavusansmono-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-droidsansmono-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-fantasquesansmono-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-firacode-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-go-mono-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-gohu-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-hack-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-hasklug-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-heavydata-nerd-font-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-hurmit-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-im-writing-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-inconsolatago-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-inconsolatalgc-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-iosevka-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-jetbrainsmono-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-lekton-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-literationmono-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-meslo-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-monoid-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-mononoki-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-mplus-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-noto-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-opendyslexic-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-profont-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-proggyclean-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-robotomono-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-sauce-code-pro-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-shuretechmono-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-spacemono-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-terminess-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-tinos-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-ubuntumono-nerd-font
brew tap homebrew/cask-fonts && brew install --cask font-victormono-nerd-font
